### ISSUE TITLE
Update Red_Hat_Enterprise_Linux_7 STIG to V2R1

### ISSUE THREAD

**Issue by angystardust** [MindPointGroup/stig-cli#7]
Hi, thanks for your software.
A new release (v2r1) of Red_Hat_Enterprise_Linux_7 STIG has been released on 9/11/2018 (https://iasecontent.disa.mil/stigs/zip/U_Red_Hat_Enterprise_Linux_7_V2R1_STIG.zip).
Is it possible to use stig-cli with this new relases?
Would it be possible to automatically update the benchmarks once a new version is released? 
Thanks
P.s.: I know the README in the data folder says to don't do it but in the meanwhile, I've upgraded the benchmark database by hand :)

**Comment by defionscode** [comment]
Hi @angystardust, if you installed via one of the packages then it's not updated yet, but if you installed from source it should already be there, take a look at https://github.com/MindPointGroup/stig-cli/blob/master/data/benchmarks/U_Red_Hat_Enterprise_Linux_7_V2R1_STIG.xml
so if you install from source and do `stig init` it should pull in v2r1. 

And yes it's absolutely possible to do auto updates, it's actually in my plan to have automated daily builds of the database (and installers) whenever a new STIG is introduced or an existing one is updated.

At the moment I'm doing some polishing with creating an RPM installer and once that is pretty then it should be straightforward to automate the above.

Obviously you use RHEL but in what OS are you using this CLI? You dont need to share if you're not comfortable just helps better understand the users of my code :)

PS there is nothing wrong, per se, about doing the updates yourself, it's just something that's not tested so YMMV. If it worked for you, great!

**Comment by angystardust** [comment]
Thanks a lot for your superfast reply. Sorry for not checking the source by myself without the need to bother you :)
By the way, fedora29 here and no issue at all. :+1 thanks again for your very useful software.
Hope to see the rpm soon both in epel and Fedora offical repos;)
